

pipeline {
    agent any

    environment {
        IMAGE_NAME = 'prajwalbambulkar/3tiernodejs-frontend'
        DOCKER_USER = 'prajwalbambulkar'
        DOCKER_PASS = '@#$Admin@#$12345'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/PrajwalBambulkar/3tiernodejs.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./frontend'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                  echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                  docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                '''
            }
        }
    }
}
